#############################################################################
# Makefile for building: agvservice
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  agvservice.pro
# Template: app
# Command: /home/ytw/Qt5.8.0/5.8/gcc_64/bin/qmake -o Makefile agvservice.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++1y -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../Qt5.8.0/5.8/gcc_64/include -I../Qt5.8.0/5.8/gcc_64/include/QtWidgets -I../Qt5.8.0/5.8/gcc_64/include/QtGui -I../Qt5.8.0/5.8/gcc_64/include/QtSql -I../Qt5.8.0/5.8/gcc_64/include/QtNetwork -I../Qt5.8.0/5.8/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I. -I../Qt5.8.0/5.8/gcc_64/mkspecs/linux-g++
QMAKE         = /home/ytw/Qt5.8.0/5.8/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = agvservice1.0.0
DISTDIR = /home/ytw/agvservice/.tmp/agvservice1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/ytw/Qt5.8.0/5.8/gcc_64/lib
LIBS          = $(SUBLIBS) -lsqlite3 -ljsoncpp -lboost_system -lboost_thread -L/home/ytw/Qt5.8.0/5.8/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5Sql -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		mapmap/mapelement.cpp \
		mapmap/mappoint.cpp \
		mapmap/mappath.cpp \
		mapmap/mapbackground.cpp \
		mapmap/onemap.cpp \
		mapmap/blockmanager.cpp \
		util/common.cpp \
		mapmap/mapmanager.cpp \
		network/sessionbuffer.cpp \
		network/session.cpp \
		network/acceptor.cpp \
		sql/sql.cpp \
		sql/cppsqlite3.cpp \
		network/tcpacceptor.cpp \
		util/qyhbuffer.cpp \
		network/tcpsession.cpp \
		agv/agv.cpp \
		network/sessionmanager.cpp \
		task/taskmaker.cpp \
		task/taskmanager.cpp \
		task/agvtasknodedothing.cpp \
		task/agvtasknode.cpp \
		task/agvtask.cpp \
		network/tcpclient.cpp \
		util/base64.cpp \
		user/msgprocess.cpp \
		user/userlogmanager.cpp \
		util/bezierarc.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		mapelement.o \
		mappoint.o \
		mappath.o \
		mapbackground.o \
		onemap.o \
		blockmanager.o \
		common.o \
		mapmanager.o \
		sessionbuffer.o \
		session.o \
		acceptor.o \
		sql.o \
		cppsqlite3.o \
		tcpacceptor.o \
		qyhbuffer.o \
		tcpsession.o \
		agv.o \
		sessionmanager.o \
		taskmaker.o \
		taskmanager.o \
		agvtasknodedothing.o \
		agvtasknode.o \
		agvtask.o \
		tcpclient.o \
		base64.o \
		msgprocess.o \
		userlogmanager.o \
		bezierarc.o \
		moc_mainwindow.o
DIST          = ../Qt5.8.0/5.8/gcc_64/mkspecs/features/spec_pre.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/common/unix.conf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/common/linux.conf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/common/sanitize.conf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base.conf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/common/g++-base.conf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/common/g++-unix.conf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/qconfig.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/qt_functions.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/qt_config.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/linux-g++/qmake.conf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/exclusive_builds.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/toolchain.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/default_pre.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/resolve_config.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/default_post.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/qml_debug.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/warn_on.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/qt.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/resources.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/moc.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/unix/opengl.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/uic.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/unix/thread.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/qmake_use.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/file_copies.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/testcase_targets.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/exceptions.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/yacc.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/lex.prf \
		agvservice.pro mainwindow.h \
		mapmap/mapelement.h \
		mapmap/mappoint.h \
		mapmap/mappath.h \
		mapmap/mapbackground.h \
		mapmap/onemap.h \
		mapmap/blockmanager.h \
		util/common.h \
		mapmap/mapmanager.h \
		network/sessionbuffer.h \
		network/protocol.h \
		network/session.h \
		network/acceptor.h \
		sql/sql.h \
		sql/cppsqlite3.h \
		network/tcpacceptor.h \
		util/qyhbuffer.h \
		network/tcpsession.h \
		agv/agv.h \
		network/sessionmanager.h \
		task/taskmaker.h \
		task/taskmanager.h \
		task/agvtasknodedothing.h \
		task/agvtasknode.h \
		task/agvtask.h \
		network/tcpclient.h \
		util/base64.h \
		user/msgprocess.h \
		user/userlogmanager.h \
		util/bezierarc.h main.cpp \
		mainwindow.cpp \
		mapmap/mapelement.cpp \
		mapmap/mappoint.cpp \
		mapmap/mappath.cpp \
		mapmap/mapbackground.cpp \
		mapmap/onemap.cpp \
		mapmap/blockmanager.cpp \
		util/common.cpp \
		mapmap/mapmanager.cpp \
		network/sessionbuffer.cpp \
		network/session.cpp \
		network/acceptor.cpp \
		sql/sql.cpp \
		sql/cppsqlite3.cpp \
		network/tcpacceptor.cpp \
		util/qyhbuffer.cpp \
		network/tcpsession.cpp \
		agv/agv.cpp \
		network/sessionmanager.cpp \
		task/taskmaker.cpp \
		task/taskmanager.cpp \
		task/agvtasknodedothing.cpp \
		task/agvtasknode.cpp \
		task/agvtask.cpp \
		network/tcpclient.cpp \
		util/base64.cpp \
		user/msgprocess.cpp \
		user/userlogmanager.cpp \
		util/bezierarc.cpp
QMAKE_TARGET  = agvservice
DESTDIR       = 
TARGET        = agvservice


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: agvservice.pro ../Qt5.8.0/5.8/gcc_64/mkspecs/linux-g++/qmake.conf ../Qt5.8.0/5.8/gcc_64/mkspecs/features/spec_pre.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/common/unix.conf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/common/linux.conf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/common/sanitize.conf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base.conf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/common/g++-base.conf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/common/g++-unix.conf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/qconfig.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/qt_functions.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/qt_config.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/linux-g++/qmake.conf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/exclusive_builds.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/toolchain.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/default_pre.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/resolve_config.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/default_post.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/qml_debug.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/warn_on.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/qt.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/resources.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/moc.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/unix/opengl.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/uic.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/unix/thread.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/qmake_use.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/file_copies.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/testcase_targets.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/exceptions.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/yacc.prf \
		../Qt5.8.0/5.8/gcc_64/mkspecs/features/lex.prf \
		agvservice.pro \
		../Qt5.8.0/5.8/gcc_64/lib/libQt5Widgets.prl \
		../Qt5.8.0/5.8/gcc_64/lib/libQt5Gui.prl \
		../Qt5.8.0/5.8/gcc_64/lib/libQt5Sql.prl \
		../Qt5.8.0/5.8/gcc_64/lib/libQt5Network.prl \
		../Qt5.8.0/5.8/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile agvservice.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
../Qt5.8.0/5.8/gcc_64/mkspecs/features/spec_pre.prf:
../Qt5.8.0/5.8/gcc_64/mkspecs/common/unix.conf:
../Qt5.8.0/5.8/gcc_64/mkspecs/common/linux.conf:
../Qt5.8.0/5.8/gcc_64/mkspecs/common/sanitize.conf:
../Qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base.conf:
../Qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf:
../Qt5.8.0/5.8/gcc_64/mkspecs/common/g++-base.conf:
../Qt5.8.0/5.8/gcc_64/mkspecs/common/g++-unix.conf:
../Qt5.8.0/5.8/gcc_64/mkspecs/qconfig.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../Qt5.8.0/5.8/gcc_64/mkspecs/features/qt_functions.prf:
../Qt5.8.0/5.8/gcc_64/mkspecs/features/qt_config.prf:
../Qt5.8.0/5.8/gcc_64/mkspecs/linux-g++/qmake.conf:
../Qt5.8.0/5.8/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../Qt5.8.0/5.8/gcc_64/mkspecs/features/exclusive_builds.prf:
../Qt5.8.0/5.8/gcc_64/mkspecs/features/toolchain.prf:
../Qt5.8.0/5.8/gcc_64/mkspecs/features/default_pre.prf:
../Qt5.8.0/5.8/gcc_64/mkspecs/features/resolve_config.prf:
../Qt5.8.0/5.8/gcc_64/mkspecs/features/default_post.prf:
../Qt5.8.0/5.8/gcc_64/mkspecs/features/qml_debug.prf:
../Qt5.8.0/5.8/gcc_64/mkspecs/features/warn_on.prf:
../Qt5.8.0/5.8/gcc_64/mkspecs/features/qt.prf:
../Qt5.8.0/5.8/gcc_64/mkspecs/features/resources.prf:
../Qt5.8.0/5.8/gcc_64/mkspecs/features/moc.prf:
../Qt5.8.0/5.8/gcc_64/mkspecs/features/unix/opengl.prf:
../Qt5.8.0/5.8/gcc_64/mkspecs/features/uic.prf:
../Qt5.8.0/5.8/gcc_64/mkspecs/features/unix/thread.prf:
../Qt5.8.0/5.8/gcc_64/mkspecs/features/qmake_use.prf:
../Qt5.8.0/5.8/gcc_64/mkspecs/features/file_copies.prf:
../Qt5.8.0/5.8/gcc_64/mkspecs/features/testcase_targets.prf:
../Qt5.8.0/5.8/gcc_64/mkspecs/features/exceptions.prf:
../Qt5.8.0/5.8/gcc_64/mkspecs/features/yacc.prf:
../Qt5.8.0/5.8/gcc_64/mkspecs/features/lex.prf:
agvservice.pro:
../Qt5.8.0/5.8/gcc_64/lib/libQt5Widgets.prl:
../Qt5.8.0/5.8/gcc_64/lib/libQt5Gui.prl:
../Qt5.8.0/5.8/gcc_64/lib/libQt5Sql.prl:
../Qt5.8.0/5.8/gcc_64/lib/libQt5Network.prl:
../Qt5.8.0/5.8/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile agvservice.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../Qt5.8.0/5.8/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h mapmap/mapelement.h mapmap/mappoint.h mapmap/mappath.h mapmap/mapbackground.h mapmap/onemap.h mapmap/blockmanager.h util/common.h mapmap/mapmanager.h network/sessionbuffer.h network/protocol.h network/session.h network/acceptor.h sql/sql.h sql/cppsqlite3.h network/tcpacceptor.h util/qyhbuffer.h network/tcpsession.h agv/agv.h network/sessionmanager.h task/taskmaker.h task/taskmanager.h task/agvtasknodedothing.h task/agvtasknode.h task/agvtask.h network/tcpclient.h util/base64.h user/msgprocess.h user/userlogmanager.h util/bezierarc.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp mapmap/mapelement.cpp mapmap/mappoint.cpp mapmap/mappath.cpp mapmap/mapbackground.cpp mapmap/onemap.cpp mapmap/blockmanager.cpp util/common.cpp mapmap/mapmanager.cpp network/sessionbuffer.cpp network/session.cpp network/acceptor.cpp sql/sql.cpp sql/cppsqlite3.cpp network/tcpacceptor.cpp util/qyhbuffer.cpp network/tcpsession.cpp agv/agv.cpp network/sessionmanager.cpp task/taskmaker.cpp task/taskmanager.cpp task/agvtasknodedothing.cpp task/agvtasknode.cpp task/agvtask.cpp network/tcpclient.cpp util/base64.cpp user/msgprocess.cpp user/userlogmanager.cpp util/bezierarc.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../Qt5.8.0/5.8/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++1y -Wall -W -dM -E -o moc_predefs.h ../Qt5.8.0/5.8/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ../Qt5.8.0/5.8/gcc_64/include/QtWidgets/QMainWindow \
		../Qt5.8.0/5.8/gcc_64/include/QtWidgets/qmainwindow.h \
		../Qt5.8.0/5.8/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qtguiglobal.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qglobal.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qlogging.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qflags.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qmutex.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qnumeric.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qtgui-config.h \
		../Qt5.8.0/5.8/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../Qt5.8.0/5.8/gcc_64/include/QtWidgets/qwidget.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qwindowdefs.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qwindowdefs_win.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobject.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstring.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qchar.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qlist.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qiterator.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qpair.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstringlist.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qregexp.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qmargins.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qpaintdevice.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qrect.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsize.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qpoint.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qpalette.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qcolor.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qrgb.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qrgba64.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qbrush.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qvector.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qmatrix.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qpolygon.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qregion.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qdatastream.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qiodevice.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qline.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qtransform.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qpainterpath.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qimage.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qpixelformat.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qpixmap.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qshareddata.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qhash.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qfont.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qfontmetrics.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qfontinfo.h \
		../Qt5.8.0/5.8/gcc_64/include/QtWidgets/qsizepolicy.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qcursor.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qkeysequence.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qevent.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qvariant.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qmap.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qdebug.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtextstream.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qlocale.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qset.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qurl.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qurlquery.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qfile.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qfiledevice.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qvector2d.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qtouchdevice.h \
		../Qt5.8.0/5.8/gcc_64/include/QtWidgets/qtabwidget.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qicon.h \
		mainwindow.h \
		moc_predefs.h \
		../Qt5.8.0/5.8/gcc_64/bin/moc
	/home/ytw/Qt5.8.0/5.8/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/ytw/Qt5.8.0/5.8/gcc_64/mkspecs/linux-g++ -I/home/ytw/agvservice -I/home/ytw/Qt5.8.0/5.8/gcc_64/include -I/home/ytw/Qt5.8.0/5.8/gcc_64/include/QtWidgets -I/home/ytw/Qt5.8.0/5.8/gcc_64/include/QtGui -I/home/ytw/Qt5.8.0/5.8/gcc_64/include/QtSql -I/home/ytw/Qt5.8.0/5.8/gcc_64/include/QtNetwork -I/home/ytw/Qt5.8.0/5.8/gcc_64/include/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../Qt5.8.0/5.8/gcc_64/bin/uic
	/home/ytw/Qt5.8.0/5.8/gcc_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../Qt5.8.0/5.8/gcc_64/include/QtWidgets/QMainWindow \
		../Qt5.8.0/5.8/gcc_64/include/QtWidgets/qmainwindow.h \
		../Qt5.8.0/5.8/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qtguiglobal.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qglobal.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qlogging.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qflags.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qmutex.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qnumeric.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qtgui-config.h \
		../Qt5.8.0/5.8/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../Qt5.8.0/5.8/gcc_64/include/QtWidgets/qwidget.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qwindowdefs.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qwindowdefs_win.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobject.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstring.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qchar.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qlist.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qiterator.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qpair.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstringlist.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qregexp.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qmargins.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qpaintdevice.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qrect.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsize.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qpoint.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qpalette.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qcolor.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qrgb.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qrgba64.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qbrush.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qvector.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qmatrix.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qpolygon.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qregion.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qdatastream.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qiodevice.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qline.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qtransform.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qpainterpath.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qimage.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qpixelformat.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qpixmap.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qshareddata.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qhash.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qfont.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qfontmetrics.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qfontinfo.h \
		../Qt5.8.0/5.8/gcc_64/include/QtWidgets/qsizepolicy.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qcursor.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qkeysequence.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qevent.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qvariant.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qmap.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qdebug.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtextstream.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qlocale.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qset.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qurl.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qurlquery.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qfile.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qfiledevice.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qvector2d.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qtouchdevice.h \
		../Qt5.8.0/5.8/gcc_64/include/QtWidgets/qtabwidget.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qicon.h \
		../Qt5.8.0/5.8/gcc_64/include/QtWidgets/QApplication \
		../Qt5.8.0/5.8/gcc_64/include/QtWidgets/qapplication.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcoreapplication.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qeventloop.h \
		../Qt5.8.0/5.8/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qguiapplication.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qinputmethod.h \
		network/acceptor.h \
		network/session.h \
		network/sessionbuffer.h \
		network/tcpsession.h \
		network/protocol.h \
		agv/agv.h \
		network/tcpacceptor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../Qt5.8.0/5.8/gcc_64/include/QtWidgets/QMainWindow \
		../Qt5.8.0/5.8/gcc_64/include/QtWidgets/qmainwindow.h \
		../Qt5.8.0/5.8/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qtguiglobal.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qglobal.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qlogging.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qflags.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qmutex.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qnumeric.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qtgui-config.h \
		../Qt5.8.0/5.8/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../Qt5.8.0/5.8/gcc_64/include/QtWidgets/qwidget.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qwindowdefs.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qwindowdefs_win.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobject.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstring.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qchar.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qlist.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qiterator.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qpair.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstringlist.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qregexp.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qmargins.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qpaintdevice.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qrect.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsize.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qpoint.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qpalette.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qcolor.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qrgb.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qrgba64.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qbrush.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qvector.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qmatrix.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qpolygon.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qregion.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qdatastream.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qiodevice.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qline.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qtransform.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qpainterpath.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qimage.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qpixelformat.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qpixmap.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qshareddata.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qhash.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qfont.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qfontmetrics.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qfontinfo.h \
		../Qt5.8.0/5.8/gcc_64/include/QtWidgets/qsizepolicy.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qcursor.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qkeysequence.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qevent.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qvariant.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qmap.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qdebug.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtextstream.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qlocale.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qset.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qurl.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qurlquery.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qfile.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qfiledevice.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qvector2d.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qtouchdevice.h \
		../Qt5.8.0/5.8/gcc_64/include/QtWidgets/qtabwidget.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qicon.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

mapelement.o: mapmap/mapelement.cpp mapmap/mapelement.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/QObject \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobject.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qglobal.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qlogging.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qflags.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qmutex.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qnumeric.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstring.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qchar.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qlist.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qiterator.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qpair.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstringlist.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qregexp.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobject_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mapelement.o mapmap/mapelement.cpp

mappoint.o: mapmap/mappoint.cpp mapmap/mappoint.h \
		mapmap/mapelement.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/QObject \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobject.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qglobal.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qlogging.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qflags.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qmutex.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qnumeric.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstring.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qchar.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qlist.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qiterator.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qpair.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstringlist.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qregexp.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobject_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mappoint.o mapmap/mappoint.cpp

mappath.o: mapmap/mappath.cpp mapmap/mappath.h \
		mapmap/mappoint.h \
		mapmap/mapelement.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/QObject \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobject.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qglobal.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qlogging.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qflags.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qmutex.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qnumeric.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstring.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qchar.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qlist.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qiterator.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qpair.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstringlist.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qregexp.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobject_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mappath.o mapmap/mappath.cpp

mapbackground.o: mapmap/mapbackground.cpp mapmap/mapbackground.h \
		mapmap/mapelement.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/QObject \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobject.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qglobal.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qlogging.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qflags.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qmutex.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qnumeric.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstring.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qchar.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qlist.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qiterator.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qpair.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstringlist.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qregexp.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobject_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mapbackground.o mapmap/mapbackground.cpp

onemap.o: mapmap/onemap.cpp mapmap/onemap.h \
		mapmap/mapbackground.h \
		mapmap/mapelement.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/QObject \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobject.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qglobal.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qlogging.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qflags.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qmutex.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qnumeric.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstring.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qchar.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qlist.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qiterator.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qpair.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstringlist.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qregexp.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobject_impl.h \
		mapmap/mappath.h \
		mapmap/mappoint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o onemap.o mapmap/onemap.cpp

blockmanager.o: mapmap/blockmanager.cpp mapmap/blockmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o blockmanager.o mapmap/blockmanager.cpp

common.o: util/common.cpp util/common.h \
		utils/Log/spdlog/spdlog.h \
		utils/Log/spdlog/common.h \
		utils/Log/spdlog/tweakme.h \
		utils/Log/spdlog/details/null_mutex.h \
		utils/Log/spdlog/fmt/fmt.h \
		utils/Log/spdlog/fmt/bundled/format.h \
		utils/Log/spdlog/fmt/bundled/format.cc \
		utils/Log/spdlog/fmt/bundled/printf.h \
		utils/Log/spdlog/fmt/bundled/ostream.h \
		utils/Log/spdlog/fmt/bundled/ostream.cc \
		utils/Log/spdlog/fmt/bundled/printf.cc \
		utils/Log/spdlog/logger.h \
		utils/Log/spdlog/sinks/base_sink.h \
		utils/Log/spdlog/details/log_msg.h \
		utils/Log/spdlog/details/os.h \
		utils/Log/spdlog/formatter.h \
		utils/Log/spdlog/details/pattern_formatter_impl.h \
		utils/Log/spdlog/sinks/sink.h \
		utils/Log/spdlog/details/logger_impl.h \
		utils/Log/spdlog/details/spdlog_impl.h \
		utils/Log/spdlog/details/registry.h \
		utils/Log/spdlog/async_logger.h \
		utils/Log/spdlog/details/async_logger_impl.h \
		utils/Log/spdlog/details/async_log_helper.h \
		utils/Log/spdlog/details/mpmc_blocking_q.h \
		utils/Log/spdlog/sinks/file_sinks.h \
		utils/Log/spdlog/details/file_helper.h \
		utils/Log/spdlog/sinks/stdout_sinks.h \
		utils/Log/spdlog/sinks/syslog_sink.h \
		utils/Log/spdlog/sinks/wincolor_sink.h \
		utils/Log/spdlog/sinks/ansicolor_sink.h \
		utils/Log/spdlog/sinks/android_sink.h \
		utils/Log/spdlog/fmt/ostr.h \
		utils/threadpool.h \
		sql/cppsqlite3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o common.o util/common.cpp

mapmanager.o: mapmap/mapmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mapmanager.o mapmap/mapmanager.cpp

sessionbuffer.o: network/sessionbuffer.cpp network/sessionbuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sessionbuffer.o network/sessionbuffer.cpp

session.o: network/session.cpp network/session.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o session.o network/session.cpp

acceptor.o: network/acceptor.cpp network/acceptor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o acceptor.o network/acceptor.cpp

sql.o: sql/sql.cpp sql/sql.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/QList \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qevent.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qtguiglobal.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qglobal.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qlogging.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qflags.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qmutex.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qnumeric.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qtgui-config.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qwindowdefs.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qwindowdefs_win.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qregion.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qrect.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qmargins.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsize.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qpoint.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qdatastream.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qiodevice.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobject.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstring.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qchar.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qlist.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qiterator.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qpair.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstringlist.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qregexp.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qkeysequence.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qvariant.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qmap.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qdebug.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qhash.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qtextstream.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qlocale.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qshareddata.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qvector.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qset.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qurl.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qurlquery.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qfile.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/qfiledevice.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qvector2d.h \
		../Qt5.8.0/5.8/gcc_64/include/QtGui/qtouchdevice.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/QVariant \
		../Qt5.8.0/5.8/gcc_64/include/QtSql/QSqlDatabase \
		../Qt5.8.0/5.8/gcc_64/include/QtSql/qsqldatabase.h \
		../Qt5.8.0/5.8/gcc_64/include/QtSql/qtsqlglobal.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/QMutex \
		../Qt5.8.0/5.8/gcc_64/include/QtSql/QSqlError \
		../Qt5.8.0/5.8/gcc_64/include/QtSql/qsqlerror.h \
		../Qt5.8.0/5.8/gcc_64/include/QtSql/QSqlRecord \
		../Qt5.8.0/5.8/gcc_64/include/QtSql/qsqlrecord.h \
		../Qt5.8.0/5.8/gcc_64/include/QtSql/QSqlQuery \
		../Qt5.8.0/5.8/gcc_64/include/QtSql/qsqlquery.h \
		../Qt5.8.0/5.8/gcc_64/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sql.o sql/sql.cpp

cppsqlite3.o: sql/cppsqlite3.cpp sql/cppsqlite3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cppsqlite3.o sql/cppsqlite3.cpp

tcpacceptor.o: network/tcpacceptor.cpp network/tcpacceptor.h \
		network/acceptor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcpacceptor.o network/tcpacceptor.cpp

qyhbuffer.o: util/qyhbuffer.cpp util/qyhbuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qyhbuffer.o util/qyhbuffer.cpp

tcpsession.o: network/tcpsession.cpp network/tcpsession.h \
		network/session.h \
		network/protocol.h \
		agv/agv.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcpsession.o network/tcpsession.cpp

agv.o: agv/agv.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o agv.o agv/agv.cpp

sessionmanager.o: network/sessionmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sessionmanager.o network/sessionmanager.cpp

taskmaker.o: task/taskmaker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o taskmaker.o task/taskmaker.cpp

taskmanager.o: task/taskmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o taskmanager.o task/taskmanager.cpp

agvtasknodedothing.o: task/agvtasknodedothing.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o agvtasknodedothing.o task/agvtasknodedothing.cpp

agvtasknode.o: task/agvtasknode.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o agvtasknode.o task/agvtasknode.cpp

agvtask.o: task/agvtask.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o agvtask.o task/agvtask.cpp

tcpclient.o: network/tcpclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcpclient.o network/tcpclient.cpp

base64.o: util/base64.cpp util/base64.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o base64.o util/base64.cpp

msgprocess.o: user/msgprocess.cpp user/msgprocess.h \
		network/protocol.h \
		network/session.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o msgprocess.o user/msgprocess.cpp

userlogmanager.o: user/userlogmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o userlogmanager.o user/userlogmanager.cpp

bezierarc.o: util/bezierarc.cpp util/bezierarc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bezierarc.o util/bezierarc.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

